site_name: Levenstein Lab Handbook
site_url: https://levensteinlab.github.io/lab-handbook
repo_url: https://github.com/LevensteinLab/Lab-Handbook
nav:
  - Policies:
    - Good Software: Policies/code_software.md
    - Health & Wellness: Policies/health_wellness.md
    - Hours & Remote Work: Policies/hours_remote_vacation.md
  - Resources:
    - Adobe: Resources/adobe.md
    - Basic Github: Resources/basic_github.md
    - GenAI: Resources/gen_ai.md
    - HPC: Resources/hpc.md
    - Mailing Lists: Resources/mailing_lists.md
    - Mental Health: Resources/mental_health.md
    - Printing: Resources/printers.md
    - pRNN Tutorial: Resources/prnn_tutorial.md
    - Recommended Reading: Resources/recommended_reading.md
    - Doing Science: Resources/science_general.md
    - Travel: Resources/travel.md
  - Meetings: meetings.md
  - Onboarding: onboarding.md
  - Contact: contact.md
