[build]
  command = "pip install -r requirements.txt && mkdocs build"
  publish = "site"

[build.environment]
  PYTHON_VERSION = "3.11"

# Optional: Configure redirects for specific protected pages
# [[redirects]]
#   from = "/protected/*"
#   to = "/protected/:splat"
#   status = 200
#   force = false